### ISSUE TITLE
讀取clob/blob發生TTC error

### ISSUE THREAD

**Issue by yuessir** [purestackorg/pure.data#1]
讀取bolb 發生TTC error
oralce 10gOracle Database 10g Enterprise Edition Release 10.2.0.4.0 - 64bi
.net core 3
有解嗎?

**Comment by purestack** [comment]
> 讀取bolb 發生TTC error
> oralce 10gOracle Database 10g Enterprise Edition Release 10.2.0.4.0 - 64bi
> .net core 3
> 有解嗎?

你在默认的PureDataConfiguration.xml可以配置相关的LobConverterClassName实现类自行实现转换，也有参考的转换例子

**Comment by yuessir** [comment]
之前已查閱,無解 貌似oralce .net provider 問題
